packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@types/node": ^22.18.12
  eslint: ^9.38.0
  typescript: 5.9.2
  prettier: ^3.6.2
  viem: "2.x"
  dotenv-cli: "^10.0.0"

linkWorkspacePackages: true
