import { getConfig } from '~/_config/wagmi';
import { ReactQueryProvider } from '~/components/providers/ReactQueryProvider';
import { ThemeProvider } from '@acme/ui/provider/theme-provider';
import { WagmiProvider } from '~/components/providers/WagmiProvider';
import { Toaster } from '@acme/ui/sonner';
import { siteName } from '~/white-label';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { headers } from 'next/headers';
import { cookieToInitialState } from 'wagmi';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: siteName,
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const wagmiInitialState = cookieToInitialState(getConfig(), (await headers()).get('cookie'));

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <WagmiProvider initialState={wagmiInitialState}>
          <ReactQueryProvider>
            <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
              <Toaster />
              {children}
            </ThemeProvider>
          </ReactQueryProvider>
        </WagmiProvider>
      </body>
    </html>
  );
}
