import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppHeader } from "@/components/layout/AppHeader";
import { ThemeProvider } from "@/components/providers/ThemeProvider";
import { WagmiProvider } from "@/components/providers/WagmiProvider";
import { ReactQueryProvider } from "@/components/providers/ReactQueryProvider";
import { cookieToInitialState } from "wagmi";
import { headers } from "next/headers";
import { siteName } from "@/white-label";
import { getConfig } from "@/_config/wagmi";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: siteName,
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const wagmiInitialState = cookieToInitialState(
    getConfig(),
    (await headers()).get("cookie")
  );

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <WagmiProvider initialState={wagmiInitialState}>
          <ReactQueryProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <AppHeader />
              {children}
            </ThemeProvider>
          </ReactQueryProvider>
        </WagmiProvider>
      </body>
    </html>
  );
}
